### ISSUE TITLE
App crashes when trying to join a meet

### ISSUE THREAD

**Issue by EmanuelBalaban** [jitsi/jitsi-meet-flutter-sdk#25]
I am not sure where to add this bug report so I will reference it here: https://github.com/jitsi/jitsi-meet/issues/14011

Seems to be an sdk issue though.

**Comment by EmanuelBalaban** [comment]
Swaped `FlutterFragmentActivity` with `FlutterActivity` and it works now. Can you please fix this? I need to use `FlutterFragmentActivity` to be able to integrate other plugins.

**Comment by gabiborlea** [comment]
I'll give it a look

**Comment by gabiborlea** [comment]
Could you please give us an example how to reproduce this issue?

**Comment by Masteribrahim1** [comment]
@gabiborlea try and make a call in release or profile mode

**Comment by saghul** [comment]
Can you reproduce it with the sample app?

**Comment by Masteribrahim1** [comment]
@saghul Yes it does when you run it on release mode and or profile mode, it crashes when you try to make a call

**Comment by saghul** [comment]
Please paste the crash when you run the sample app in release mode, we don't support profile mode.

**Comment by Masteribrahim1** [comment]
@saghul release mode doesn't give error message, just try it at your end

**Comment by saghul** [comment]
I'm confused, does or does it not crash for you?

**Comment by Masteribrahim1** [comment]
@saghul it crashes for me and i have tried everything. What do you suggest?

**Comment by saghul** [comment]
Share the crash logs.

**Comment by EarbajEvidentBD** [comment]
E/AndroidRuntime( 6008): java.lang.RuntimeException: Unable to start activity ComponentInfo{net.attendancekeeper.app/org.jitsi.jitsi_meet_flutter_sdk.WrapperJitsiMeetActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactInstanceManager.createReactContextInBackground()' on a null object reference
E/AndroidRuntime( 6008): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3762)
E/AndroidRuntime( 6008): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3929)
E/AndroidRuntime( 6008): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime( 6008): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6008): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6008): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
E/AndroidRuntime( 6008): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6008): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime( 6008): 	at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime( 6008): 	at android.app.ActivityThread.main(ActivityThread.java:8302)
E/AndroidRuntime( 6008): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6008): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/AndroidRuntime( 6008): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
E/AndroidRuntime( 6008): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactInstanceManager.createReactContextInBackground()' on a null object reference
E/AndroidRuntime( 6008): 	at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:507)
E/AndroidRuntime( 6008): 	at org.jitsi.meet.sdk.JitsiMeetView.createReactRootView(JitsiMeetView.java:181)
E/AndroidRuntime( 6008): 	at org.jitsi.meet.sdk.JitsiMeetView.setProps(JitsiMeetView.java:221)
E/AndroidRuntime( 6008): 	at org.jitsi.meet.sdk.JitsiMeetView.join(JitsiMeetView.java:156)
E/AndroidRuntime( 6008): 	at org.jitsi.meet.sdk.JitsiMeetActivity.join(JitsiMeetActivity.java:218)
E/AndroidRuntime( 6008): 	at org.jitsi.meet.sdk.JitsiMeetActivity.initialize(JitsiMeetActivity.java:264)
E/AndroidRuntime( 6008): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:144)
E/AndroidRuntime( 6008): 	at org.jitsi.jitsi_meet_flutter_sdk.WrapperJitsiMeetActivity.onCreate(WrapperJitsiMeetActivity.kt:39)
E/AndroidRuntime( 6008): 	at android.app.Activity.performCreate(Activity.java:8191)
E/AndroidRuntime( 6008): 	at android.app.Activity.performCreate(Activity.java:8159)
E/AndroidRuntime( 6008): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
E/AndroidRuntime( 6008): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3735)
E/AndroidRuntime( 6008): 	... 12 more
D/OOMEventManagerFK( 6008): checkEventAndDumpForJE: 0
I/Process ( 6008): Sending signal. PID: 6008 SIG: 9

this is the log on Debug mode in release mode there is nothing App crash when join the meeting with this crash logs

**Comment by saghul** [comment]
What SDK version are you using?

**Comment by EarbajEvidentBD** [comment]
> What SDK version are you using?

Flutter 3.38.5 • Dart 3.10.4 • DevTools 2.51.1

Still facing the same issue after upgrade jitsi to lattest
