### ISSUE TITLE
could anyone tell how to fix the issues of jitsi meet app crashing on join meeting

### ISSUE THREAD

**Issue by ArunKarthikAnandKumar** [jitsi/jitsi-meet-flutter-sdk#41]
this is my stack trace
D/JITSI_MEET_PLUGIN( 8417): Joining Room: 16008197
D/JITSI_MEET_PLUGIN( 8417): Server URL: https://meet.jit.si, https://meet.jit.si
D/OrientationModule( 8417): onActivityPaused
D/libMEOW ( 8417): meow new tls: 0xb4000078798c7000
D/libMEOW ( 8417): applied 1 plugins for [rkDigiLed.shop.com]:
D/libMEOW ( 8417):   plugin 1: [libMEOW_gift.so]: 0xb40000794730e2c0
D/libMEOW ( 8417): rebuild call chain: 0xb40000787920d100
D/libMEOW ( 8417): meow delete tls: 0xb4000078798c7000
D/AppCompatDelegate( 8417): Checking for metadata for AppLocalesMetadataHolderService : Service not found
D/OrientationModule( 8417): onActivityCreated
W/igiLed.shop.com( 8417): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/igiLed.shop.com( 8417): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
I/org.webrtc.Logging( 8417): EglBase14Impl: Using OpenGL ES version 2
D/ReactInstanceManagerHolder( 8417): initializing RN with Activity
W/igiLed.shop.com( 8417): Accessing hidden method Landroid/content/Context;->destroy()V (blocked, linking, denied)
W/igiLed.shop.com( 8417): Accessing hidden method Landroid/content/Context;->destroy()V (blocked, linking, denied)
D/AndroidRuntime( 8417): Shutting down VM
E/AndroidRuntime( 8417): FATAL EXCEPTION: main
E/AndroidRuntime( 8417): Process: rkDigiLed.shop.com, PID: 8417
E/AndroidRuntime( 8417): java.lang.RuntimeException: Unable to start activity ComponentInfo{rkDigiLed.shop.com/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: android.view.InflateException: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/AndroidRuntime( 8417): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3867)
E/AndroidRuntime( 8417): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4009)
E/AndroidRuntime( 8417): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
E/AndroidRuntime( 8417): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 8417): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 8417): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2465)
E/AndroidRuntime( 8417): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8417): 	at android.os.Looper.loopOnce(Looper.java:240)
E/AndroidRuntime( 8417): 	at android.os.Looper.loop(Looper.java:351)
E/AndroidRuntime( 8417): 	at android.app.ActivityThread.main(ActivityThread.java:8370)
E/AndroidRuntime( 8417): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8417): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
E/AndroidRuntime( 8417): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/AndroidRuntime( 8417): Caused by: android.view.InflateException: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/AndroidRuntime( 8417): Caused by: android.view.InflateException: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/AndroidRuntime( 8417): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 8417): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime( 8417): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/AndroidRuntime( 8417): 	at android.view.LayoutInflater.createView(LayoutInflater.java:857)
E/AndroidRuntime( 8417): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1009)
E/AndroidRuntime( 8417): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:964)
E/AndroidRuntime( 8417): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
E/AndroidRuntime( 8417): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1087)
E/AndroidRuntime( 8417): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
E/AndroidRuntime( 8417): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
E/AndroidRuntime( 8417): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
E/AndroidRuntime( 8417): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
E/AndroidRuntime( 8417): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
E/AndroidRuntime( 8417): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:103)
E/AndroidRuntime( 8417): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/AndroidRuntime( 8417): 	at android.app.Activity.performCreate(Activity.java:8422)
E/AndroidRuntime( 8417): 	at android.app.Activity.performCreate(Activity.java:8395)
E/AndroidRuntime( 8417): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
E/AndroidRuntime( 8417): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3840)
E/AndroidRuntime( 8417): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4009)
E/AndroidRuntime( 8417): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
E/AndroidRuntime( 8417): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 8417): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 8417): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2465)
E/AndroidRuntime( 8417): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8417): 	at android.os.Looper.loopOnce(Looper.java:240)
E/AndroidRuntime( 8417): 	at android.os.Looper.loop(Looper.java:351)
E/AndroidRuntime( 8417): 	at android.app.ActivityThread.main(ActivityThread.java:8370)
E/AndroidRuntime( 8417): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8417): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
E/AndroidRuntime( 8417): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/AndroidRuntime( 8417): Caused by: java.lang.VerifyError: Verifier rejected class com.oblador.performance.PerformanceModule: void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMark) failed to verify: void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMark): [0x27] register v1 has type Reference: com.facebook.react.bridge.WritableMap but expected Reference: com.facebook.react.bridge.ReadableMap
E/AndroidRuntime( 8417):  void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMetric) failed to verify: void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMetric): [0x30] register v1 has type Reference: com.facebook.react.bridge.WritableMap but expected Reference: com.facebook.react.bridge.ReadableMap (declaration of 'com.oblador.performance.PerformanceModule' appears in /data/app/~~7-vjbXvpBklC4CeuOIV9qg==/rkDigiLed.shop.com-gBHvIhjPxkXg0Xrxv3qF2A==/base.apk!classes9.dex)
E/AndroidRuntime( 8417): 	at com.oblador.performance.PerformancePackage.<init>(PerformancePackage.java:19)
E/AndroidRuntime( 8417): 	at org.jitsi.meet.sdk.ReactInstanceManagerHolder.getReactNativePackages(ReactInstanceManagerHolder.java:89)
E/AndroidRuntime( 8417): 	at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:253)
E/AndroidRuntime( 8417): 	at org.jitsi.meet.sdk.JitsiMeetView.initialize(JitsiMeetView.java:201)
E/AndroidRuntime( 8417): 	at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:102)
E/AndroidRuntime( 8417): 	... 30 more
E/JitsiMeetSDK( 8417): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK( 8417): java.lang.RuntimeException: Unable to start activity ComponentInfo{rkDigiLed.shop.com/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: android.view.InflateException: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3867)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4009)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2465)
E/JitsiMeetSDK( 8417): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK( 8417): 	at android.os.Looper.loopOnce(Looper.java:240)
E/JitsiMeetSDK( 8417): 	at android.os.Looper.loop(Looper.java:351)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.main(ActivityThread.java:8370)
E/JitsiMeetSDK( 8417): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 8417): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
E/JitsiMeetSDK( 8417): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/JitsiMeetSDK( 8417): Caused by: android.view.InflateException: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK( 8417): Caused by: android.view.InflateException: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK( 8417): Caused by: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK( 8417): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/JitsiMeetSDK( 8417): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.createView(LayoutInflater.java:857)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1009)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:964)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1087)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
E/JitsiMeetSDK( 8417): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
E/JitsiMeetSDK( 8417): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
E/JitsiMeetSDK( 8417): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:103)
E/JitsiMeetSDK( 8417): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK( 8417): 	at android.app.Activity.performCreate(Activity.java:8422)
E/JitsiMeetSDK( 8417): 	at android.app.Activity.performCreate(Activity.java:8395)
E/JitsiMeetSDK( 8417): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3840)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4009)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2465)
E/JitsiMeetSDK( 8417): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK( 8417): 	at android.os.Looper.loopOnce(Looper.java:240)
E/JitsiMeetSDK( 8417): 	at android.os.Looper.loop(Looper.java:351)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.main(ActivityThread.java:8370)
E/JitsiMeetSDK( 8417): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 8417): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
E/JitsiMeetSDK( 8417): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/JitsiMeetSDK( 8417): Caused by: java.lang.VerifyError: Verifier rejected class com.oblador.performance.PerformanceModule: void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMark) failed to verify: void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMark): [0x27] register v1 has type Reference: com.facebook.react.bridge.WritableMap but expected Reference: com.facebook.react.bridge.ReadableMap
E/JitsiMeetSDK( 8417):  void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMetric) failed to verify: void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMetric): [0x30] register v1 has type Reference: com.facebook.react.bridge.WritableMap but expected Reference: com.facebook.react.bridge.ReadableMap (declaration of 'com.oblador.performance.PerformanceModule' appears in /data/app/~~7-vjbXvpBklC4CeuOIV9qg==/rkDigiLed.shop.com-gBHvIhjPxkXg0Xrxv3qF2A==/base.apk!classes9.dex)
E/JitsiMeetSDK( 8417): 	at com.oblador.performance.PerformancePackage.<init>(PerformancePackage.java:19)
E/JitsiMeetSDK( 8417): 	at org.jitsi.meet.sdk.ReactInstanceManagerHolder.getReactNativePackages(ReactInstanceManagerHolder.java:89)
E/JitsiMeetSDK( 8417): 	at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:253)
E/JitsiMeetSDK( 8417): 	at org.jitsi.meet.sdk.JitsiMeetView.initialize(JitsiMeetView.java:201)
E/JitsiMeetSDK( 8417): 	at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:102)
E/JitsiMeetSDK( 8417): 	... 30 more
E/JitsiMeetSDK( 8417): 
E/JitsiMeetSDK( 8417): java.lang.RuntimeException: Unable to start activity ComponentInfo{rkDigiLed.shop.com/com.gunschu.jitsi_meet.JitsiMeetPluginActivity}: android.view.InflateException: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3867)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4009)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2465)
E/JitsiMeetSDK( 8417): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK( 8417): 	at android.os.Looper.loopOnce(Looper.java:240)
E/JitsiMeetSDK( 8417): 	at android.os.Looper.loop(Looper.java:351)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.main(ActivityThread.java:8370)
E/JitsiMeetSDK( 8417): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 8417): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
E/JitsiMeetSDK( 8417): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/JitsiMeetSDK( 8417): Caused by: android.view.InflateException: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK( 8417): Caused by: android.view.InflateException: Binary XML file line #9 in rkDigiLed.shop.com:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK( 8417): Caused by: java.lang.reflect.InvocationTargetException
E/JitsiMeetSDK( 8417): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/JitsiMeetSDK( 8417): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.createView(LayoutInflater.java:857)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1009)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:964)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1087)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
E/JitsiMeetSDK( 8417): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
E/JitsiMeetSDK( 8417): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
E/JitsiMeetSDK( 8417): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
E/JitsiMeetSDK( 8417): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:103)
E/JitsiMeetSDK( 8417): 	at com.gunschu.jitsi_meet.JitsiMeetPluginActivity.onCreate(JitsiMeetPluginActivity.kt:92)
E/JitsiMeetSDK( 8417): 	at android.app.Activity.performCreate(Activity.java:8422)
E/JitsiMeetSDK( 8417): 	at android.app.Activity.performCreate(Activity.java:8395)
E/JitsiMeetSDK( 8417): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3840)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4009)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK( 8417): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2465)
E/JitsiMeetSDK( 8417): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK( 8417): 	at android.os.Looper.loopOnce(Looper.java:240)
E/JitsiMeetSDK( 8417): 	at android.os.Looper.loop(Looper.java:351)
E/JitsiMeetSDK( 8417): 	at android.app.ActivityThread.main(ActivityThread.java:8370)
E/JitsiMeetSDK( 8417): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK( 8417): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
E/JitsiMeetSDK( 8417): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/JitsiMeetSDK( 8417): Caused by: java.lang.VerifyError: Verifier rejected class com.oblador.performance.PerformanceModule: void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMark) failed to verify: void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMark): [0x27] register v1 has type Reference: com.facebook.react.bridge.WritableMap but expected Reference: com.facebook.react.bridge.ReadableMap
E/JitsiMeetSDK( 8417):  void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMetric) failed to verify: void com.oblador.performance.PerformanceModule.emit(com.oblador.performance.PerformanceMetric): [0x30] register v1 has type Reference: com.facebook.react.bridge.WritableMap but expected Reference: com.facebook.react.bridge.ReadableMap (declaration of 'com.oblador.performance.PerformanceModule' appears in /data/app/~~7-vjbXvpBklC4CeuOIV9qg==/rkDigiLed.shop.com-gBHvIhjPxkXg0Xrxv3qF2A==/base.apk!classes9.dex)
E/JitsiMeetSDK( 8417): 	at com.oblador.performance.PerformancePackage.<init>(PerformancePackage.java:19)
E/JitsiMeetSDK( 8417): 	at org.jitsi.meet.sdk.ReactInstanceManagerHolder.getReactNativePackages(ReactInstanceManagerHolder.java:89)
E/JitsiMeetSDK( 8417): 	at org.jitsi.meet.sdk.ReactInstanceManagerHolder.initReactInstanceManager(ReactInstanceManagerHolder.java:253)
E/JitsiMeetSDK( 8417): 	at org.jitsi.meet.sdk.JitsiMeetView.initialize(JitsiMeetView.java:201)
E/JitsiMeetSDK( 8417): 	at org.jitsi.meet.sdk.JitsiMeetView.<init>(JitsiMeetView.java:102)
E/JitsiMeetSDK( 8417): 	... 30 more
I/Process ( 8417): Sending signal. PID: 8417 SIG: 9

**Comment by yash-pietech** [comment]
@ArunKarthikAnandKumar please check this comment , it is not solution but you can check if its works for you 
https://github.com/jitsi/jitsi-meet-flutter-sdk/issues/37#issuecomment-1882974623

**Comment by bbombardier** [comment]
Same thing for me. iOS works fine, android emulator crashes every time I join a meeting

**Comment by Biven-Codenomad** [comment]
@ArunKarthikAnandKumar have you got any solution for this issue?
