### ISSUE TITLE
Application crashing when starting the meeting in android

### ISSUE THREAD

**Issue by Adil-Ashfaq35** [jitsi/jitsi-meet-flutter-sdk#68]
when joining the call the application crahes

**Comment by saghul** [comment]
Please share the `adb logcat` output when the crash happens.

**Comment by Adil-Ashfaq35** [comment]
Exception thrown during dispatchAppVisibility Window{2504171 u0 com.medchois.doctorapp/org.jitsi.jitsi_meet_flutter_sdk.WrapperJitsiMeetActivity EXITING}
android.os.DeadObjectException
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact(BinderProxy.java:639)
at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:675)
at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3498)
at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1292)
at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:420)
at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:7970)
at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:6549)
at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:6491)
at com.android.server.wm.Transition.finishTransition(Transition.java:1331)
at com.android.server.wm.TransitionController.finishTransition(TransitionController.java:977)
at com.android.server.wm.WindowOrganizerController.finishTransition(WindowOrganizerController.java:438)
at android.window.IWindowOrganizerController$Stub.onTransact(IWindowOrganizerController.java:304)
at com.android.server.wm.WindowOrganizerController.onTransact(WindowOrganizerController.java:207)
at android.os.Binder.execTransactInternal(Binder.java:1351)
at android.os.Binder.execTransact(Binder.java:1282)
2024-06-03 16:53:27.190  1827-2941  Process                 system_server                        W  Unable to open /proc/10546/status
2024-06-03 16:53:27.190  1827-2941  WindowManager           system_server                        W  The process may be dead, tid:10546,tgid:-1

**Comment by saghul** [comment]
I don't think we've ever seen this one.

Do you have a test project that reproeuces the problem?

**Comment by Adil-Ashfaq35** [comment]
Problem is when i am runing the project in release mode and try to join the meeting. in debug mode it works fine

**Comment by Adil-Ashfaq35** [comment]
@saghul when i join the call in release mode it shows black screen and crash the app

**Comment by Adil-Ashfaq35** [comment]
No i did not used the sample app. But I solved the issue by added proguard rules and by adding skrinResources false. i have my own server of jitsi deployed and two different app for call. but when I joined the call now the mike is muted always even after opening it and video is also not showing properly.

**Comment by saghul** [comment]
Please let's not mix issues.

Open a new one please, and provide logs.
