### ISSUE TITLE
issue with the serverURL

### ISSUE THREAD

**Issue by hvmq** [jitsi/jitsi-meet-flutter-sdk#70]
Tôi đang gặp vấn đề về lỗi liên quan đến serverUrl, nó báo rằng improperly formatted, tôi chưa tìm được nguyên nhân

source code: 
` Future createOrJoinCallJitsi(String roomId, String roomName) async {
    final jitsiMeet = JitsiMeet();
    final configOverrides = {
      'startWithAudioMuted': true,
      'startWithVideoMuted': true,
      'subject': roomName,
    };

    final options = JitsiMeetConferenceOptions(
      serverURL: 'https://meet.jit.si',
      room: roomId,
      configOverrides: configOverrides,
      featureFlags: {'unsaferoomwarning.enabled': false},
      userInfo: JitsiMeetUserInfo(
        displayName: currentUser.fullName,
        email: currentUser.email ?? currentUser.phone ?? '',
        avatar: currentUser.avatarPath ?? '',
      ),
    );
    await jitsiMeet.join(options);
  }`

error log:
`E/DartMessenger(20338): Uncaught exception in binary message listener
E/DartMessenger(20338): java.net.MalformedURLException: no protocol: 
E/DartMessenger(20338): 	at java.net.URL.<init>(URL.java:601)
E/DartMessenger(20338): 	at java.net.URL.<init>(URL.java:498)
E/DartMessenger(20338): 	at java.net.URL.<init>(URL.java:447)
E/DartMessenger(20338): 	at org.jitsi.jitsi_meet_flutter_sdk.JitsiMeetPlugin.join(JitsiMeetPlugin.kt:83)
E/DartMessenger(20338): 	at org.jitsi.jitsi_meet_flutter_sdk.JitsiMeetPlugin.onMethodCall(JitsiMeetPlugin.kt:41)
E/DartMessenger(20338): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/DartMessenger(20338): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/DartMessenger(20338): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/DartMessenger(20338): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/DartMessenger(20338): 	at android.os.Handler.handleCallback(Handler.java:938)
E/DartMessenger(20338): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(20338): 	at android.os.Looper.loopOnce(Looper.java:226)
E/DartMessenger(20338): 	at android.os.Looper.loop(Looper.java:313)
E/DartMessenger(20338): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/DartMessenger(20338): 	at java.lang.reflect.Method.invoke(Native Method)
`

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[√] Android Studio (version 2022.3)
[√] Connected device (3 available)
[√] Network resources

I reset my system and setup flutter but still its giving me the issue. Thank you for looking

**Comment by saghul** [comment]
What plugin version are you using?

**Comment by hvmq** [comment]
Sometimes it works fine and joins the meeting normally, sometimes it logs the error as I mentioned above

**Comment by saghul** [comment]
@Calinteodor can you PTAL?

**Comment by hvmq** [comment]
@saghul  Do you know how I should fix it?

**Comment by Calinteodor** [comment]
Our Sample app is using ^0.4.2 and everything works as expected. 
Please check it for yourself and see if you get the same result.

https://github.com/jitsi/jitsi-meet-sdk-samples/tree/master/flutter
