### ISSUE TITLE
My App crashes when joining a meet despite adding the proguard rules

### ISSUE THREAD

**Issue by FulbertoDev** [jitsi/jitsi-meet-flutter-sdk#93]
2024-10-28 22:47:50.925 20669-20669 JitsiMeetSDK            fr.etutorat.etutorat                 E  JitsiMeetUncaughtExceptionHandler FATAL ERROR (Ask Gemini)
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jitsi/jitsi_meet_flutter_sdk/WrapperJitsiMeetActivity;
                                                                                                    	at org.jitsi.jitsi_meet_flutter_sdk.JitsiMeetPlugin.join(JitsiMeetPlugin.kt:130)
                                                                                                    	at org.jitsi.jitsi_meet_flutter_sdk.JitsiMeetPlugin.onMethodCall(JitsiMeetPlugin.kt:42)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:790)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:210)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7080)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
                                                                                                    Caused by: java.lang.ClassNotFoundException: org.jitsi.jitsi_meet_flutter_sdk.WrapperJitsiMeetActivity
                                                                                                    	at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                                                    	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at org.jitsi.jitsi_meet_flutter_sdk.JitsiMeetPlugin.join(JitsiMeetPlugin.kt:130) 
                                                                                                    	at org.jitsi.jitsi_meet_flutter_sdk.JitsiMeetPlugin.onMethodCall(JitsiMeetPlugin.kt:42) 
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267) 
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292) 
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319) 
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:790) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loop(Looper.java:210) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7080) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863) 
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jitsi/meet/sdk/JitsiMeetActivity;
                                                                                                    	at org.jitsi.jitsi_meet_flutter_sdk.JitsiMeetPlugin.join(JitsiMeetPlugin.kt:130) 
                                                                                                    	at org.jitsi.jitsi_meet_flutter_sdk.JitsiMeetPlugin.onMethodCall(JitsiMeetPlugin.kt:42) 
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267) 
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292) 
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319) 
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:790) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loop(Looper.java:210) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7080) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: org.jitsi.meet.sdk.JitsiMeetActivity
                                                                                                    	at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                                                    	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at org.jitsi.jitsi_meet_flutter_sdk.JitsiMeetPlugin.join(JitsiMeetPlugin.kt:130) 
                                                                                                    	at org.jitsi.jitsi_meet_flutter_sdk.JitsiMeetPlugin.onMethodCall(JitsiMeetPlugin.kt:42) 
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267) 
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292) 
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319) 
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:790) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loop(Looper.java:210) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7080) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863) 
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/fragment/app/FragmentActivity;
                                                                                                    	at com.xamdesign.safe_device.LocationAssistantListener.<init>(SafeDevicePlugin.java:101)
                                                                                                    	at com.xamdesign.safe_device.SafeDevicePlugin.onAttachedToEngine(SafeDevicePlugin.java:34)
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:147)
                                                                                                    	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:64)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
                                                                                                    	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1336)
                                                                                                    	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:219)
                                                                                                    	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:638)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7314)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7305)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2959)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3084)
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1781)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:210) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7080) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: androidx.fragment.app.FragmentActivity
                                                                                                    	at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                                                    	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.xamdesign.safe_device.LocationAssistantListener.<init>(SafeDevicePlugin.java:101) 
                                                                                                    	at com.xamdesign.safe_device.SafeDevicePlugin.onAttachedToEngine(SafeDevicePlugin.java:34) 
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:147) 
                                                                                                    	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:64) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80) 
                                                                                                    	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1336) 
                                                                                                    	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:219) 
                                                                                                    	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:638) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7314) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7305) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2959) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3084) 
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1781) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:210) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7080) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863) 
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/activity/ComponentActivity;
                                                                                                    	at com.xamdesign.safe_device.LocationAssistantListener.<init>(SafeDevicePlugin.java:101) 
                                                                                                    	at com.xamdesign.safe_device.SafeDevicePlugin.onAttachedToEngine(SafeDevicePlugin.java:34) 
                                                                                                    	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:147) 
                                                                                                    	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:64) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80) 
                                                                                                    	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1336) 
                                                                                                    	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:219) 
                                                                                                    	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:638) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7314) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7305) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2959) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3084) 
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1781) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:210) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7080) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: androidx.activity.
2024-10-28 22:47:50.997 20669-20669 Process                 fr.etutorat.etutorat                 I  Sending signal. PID: 20669 SIG: 9

**Comment by FulbertoDev** [comment]
On real device

**Comment by saghul** [comment]
What proguard rules did you use?

**Comment by FulbertoDev** [comment]
> What proguard rules did you use?
This one. I take it from one of your comment in similar issue.
`https://github.com/jitsi/jitsi-meet/blob/master/android/app/proguard-rules.pro`

**Comment by saghul** [comment]
I haven't herad of that plugin. Can you reproduce the problem compiling the sample app?

**Comment by FulbertoDev** [comment]
When I use the sample app, the problem didn't occurs.

**Comment by saghul** [comment]
Can you create a small sample that reproduces the problem?
